### PR TITLE
fix(langselector): notify is wrong when set region

### PR DESCRIPTION
**Pull request by Decodetalkers**
Log:

### CODE REVIEW

**Comment by Decodetalkers** [comment]
追加文案，大概是系统区域变化，请重启

**Review by BLumia — APPROVED** [review]

**Comment by kegechen** [comment]
怎么总是忘了提上一下 issue
https://github.com/linuxdeepin/developer-center/issues/5225

**Comment by Decodetalkers** [comment]
翻译没有更新因为

**Pull request merged**
