### PR TITLE
fix: fix build with ddcutil 2.0

### PR DESCRIPTION
**Pull request by wineee**
fix: build

from https://gitlab.archlinux.org/archlinux/packaging/packages/deepin-daemon/-/blob/18e60cd055a58841df29c69b8446dc58eeea9af1/ddcutil-2.patch

but maybe here have better solution

### CODE REVIEW

**Review by dengbo11 — APPROVED** [review]

**Comment by wineee** [comment]
@dengbo11 删掉这两行是可以接受的吗？

**Comment by wineee** [comment]
https://www.ddcutil.com/c_api_200/

**Comment by wineee** [comment]
https://github.com/linuxdeepin/dde-daemon/pull/623

**Pull request closed without merging**
