### PR TITLE
fix: archlinux build error

### PR DESCRIPTION
**Pull request by hudeng-go**
高版本ddcutil需要单独添加ddcutil_types.h才能保证cgo能正常构建

log:

### CODE REVIEW

**Comment by hudeng-go** [comment]
需要https://github.com/deepin-community/ddcutil/pull/1 先集成。

**Review by wineee — APPROVED** [review]

**Comment by wineee** [comment]
等下， deepin 构建挂了

**Review by wineee — CHANGES_REQUESTED** [review]
47s] cgo-gcc-prolog:70:33: warning: unused variable '_cgo_a' [-Wunused-variable]
[  247s] cgo-gcc-prolog: In function '_cgo_a5a61b95af5a_Cfunc_setspent':
[  247s] cgo-gcc-prolog:123:33: warning: unused variable '_cgo_a' [-Wunused-variable]
[  247s] # github.com/linuxdeepin/dde-daemon/accounts1
[  247s] reminder_info.c: In function '_count_utmpx':
[  247s] reminder_info.c:45:13: warning: 'strcmp' argument 2 declared attribute 'nonstring' [-Wstringop-overread]
[  247s]    45 |         if (strcmp(user, u->ut_user) != 0) {
[  247s]       |             ^~~~~~~~~~~~~~~~~~~~~~~~
[  247s] In file included from /usr/include/utmpx.h:31,
[  247s]                  from reminder_info.h:8,
[  247s]                  from reminder_info.c:5:
[  247s] /usr/include/aarch64-linux-gnu/bits/utmpx.h:63:8: note: argument 'ut_user' declared here
[  247s]    63 |   char ut_user[__UT_NAMESIZE]
[  247s]       |        ^~~~~~~
[  250s] make[1]: Leaving directory '/usr/src/packages/BUILD'
[  250s] dh_auto_build: error: make -j16 "INSTALL=install --strip-program=true" returned exit code 2
[  250s] make: *** [debian/rules:18: build] Error 25

**Review by zsien — APPROVED** [review]

**Review by wineee — DISMISSED** [review]

**Comment by wineee** [comment]
这个 pr 可以合吗？

**Review by justforlxz — APPROVED** [review]

**Pull request merged**
