### PR TITLE
Make install_to_hicolor.py can run with Python older then 3.5

### PR DESCRIPTION
**Pull request by zhtengw**
Fix issue #38.

### CODE REVIEW

**Comment by jouyouyun** [comment]
For python2?

**Comment by jouyouyun** [comment]
Ok, please modify the commit message to: "chore: make install_to_hicolor.py compatibility with older python version"

The commit message format see: https://github.com/conventional-changelog/conventional-changelog/blob/a5505865ff3dd710cf757f50530e73ef0ca641da/conventions/angular.md.

Thanks!

**Comment by zhtengw** [comment]
I have modified the message. @jouyouyun

**Comment by jouyouyun** [comment]
Merged!

**Pull request closed without merging**
